---
apiVersion: v1
kind: Service
metadata:
  name: metadata
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: metadata
      prefix: /api/metadata/
      service: metadata-service:8080

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: metadata-service