---
apiVersion: v1
kind: Service
metadata:
  name: accounting-storage
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: accounting_storage
      prefix: /api/accounting/storage/
      service: accounting-storage-service:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  selector:
    app: accounting-storage-service