---
persistence:
  enabled: true
  size: 25Gi
  storageClassName: rbd
  accessModes:
  - ReadWriteOnce

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
  datasources:
    enabled: true
    label: grafana_datasource