---
apiVersion: v1
kind: Service
metadata:
  name: app-abacus
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app_abacus
      prefix: /api/app/compute/abacus/
      service: app-abacus-service:8080

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: app-abacus-service