---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-monitor
  labels:
    app: kubernetes-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-monitor
  template:
    metadata:
      labels:
        app: kubernetes-monitor
    spec:
      containers:
      - name: kubernetes-monitor
        image: registry.cloud.sdu.dk/sdu-cloud/kubernetes-monitor-service:0.1.1
        command:
        - /opt/service/bin/service
        - --config-dir
        - /etc/refresh-token
        - --config-dir
        - /etc/token-validation
        - --config-dir
        - /etc/psql
        volumeMounts:
        - mountPath: /etc/refresh-token
          name: refresh-token
        - mountPath: /etc/token-validation
          name: token-validation
        - mountPath: /etc/psql
          name: kubernetes-monitor-psql
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

      volumes:
      - name: refresh-token
        secret:
          optional: false
          secretName: kubernetes-monitor-refresh-token
      - name: token-validation
        configMap:
          name: token-validation
      - name: kubernetes-monitor-psql
        secret:
          optional: false
          secretName: kubernetes-monitor-psql

      imagePullSecrets:
        - name: esci-docker
