---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: kubernetes-monitor-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete", "patch", "create", "update"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-monitor-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubernetes-monitor
    apiGroup: ""
roleRef:
  kind: Role
  name: kubernetes-monitor-role
  apiGroup: ""
