---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-monitor
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: kubernetes-monitor
      prefix: ^/api/kubernetes/monitor(/.*)?$
      prefix_regex: true
      service: kubernetes-monitor:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-monitor
