---
apiVersion: v1
kind: Service
metadata:
  name: pong
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: pong
      prefix: ^/api/pong(/.*)?$
      prefix_regex: true
      service: pong:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pong
