---
apiVersion: v1
kind: Service
metadata:
  name: accounting-compute
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: accounting_compute
      prefix: /api/accounting/compute/
      service: accounting-compute:8080

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  selector:
    app: accounting-compute