---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webclient-deployment
  labels:
    app: webclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webclient
  template:
    metadata:
      labels:
        app: webclient
    spec:
      containers:
      - name: webclient
        image: registry.cloud.sdu.dk/sdu-cloud/webclient:0.2.0
        volumeMounts:
        - mountPath: /etc/service
          name: webclient-refresh-token

      volumes:
      - name: webclient-refresh-token
        secret:
          optional: false
          secretName: webclient-refresh-token

      imagePullSecrets:
        - name: esci-docker
