---
apiVersion: v1
kind: Service
metadata:
  name: app-orchestrator
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app-orchestrator
      prefix: ^/api/app/orchestrator(/.*)?$
      prefix_regex: true
      service: app-orchestrator:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-orchestrator
