---
apiVersion: v1
kind: Service
metadata:
  name: activity
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: activity
      prefix: /api/activity/
      service: activity-service:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: activity-service