---
apiVersion: v1
kind: Service
metadata:
  name: contact-book
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: contact-book
      prefix: ^/api/contact/book(/.*)?$
      prefix_regex: true
      service: contact-book:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: contact-book
