apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job2
spec:
  minAvailable: 3
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 6
      name: "job2"
      template:
        metadata:
          name: job2
        spec:
          initContainers:
            - image: alpine:latest
              imagePullPolicy: IfNotPresent
              name: ucloud-compat
              resources:
                requests:
                  cpu: "100m"
              command:
                - /bin/sh
                - -c
                - |
                  echo $VC_TASK_INDEX > /etc/ucloud/rank.txt;
                  cat /etc/volcano/*_NUM > /etc/ucloud/number_of_nodes.txt;
                  cat /etc/volcano/*.host > /etc/ucloud/nodes.txt;
                  idx=0;
                  while IFS="" read -r p || [ -n "$p" ]
                  do
                    printf '%s\n' "$p" > /etc/ucloud/node-$idx.txt;
                    idx=$((idx + 1))
                  done < /etc/ucloud/nodes.txt;
              volumeMounts:
                - name: ucloud-multinode
                  readOnly: false
                  mountPath: /etc/ucloud
          containers:
            - image: alpine:latest
              imagePullPolicy: IfNotPresent
              name: alpine
              resources:
                requests:
                  cpu: "100m"
              command:
              - /bin/sh
              - -c
              - |
                while [ ! -f /tmp/sleep.txt ]; do sleep 1; done
              volumeMounts:
                - name: ucloud-multinode
                  readOnly: true
                  mountPath: /etc/ucloud
          restartPolicy: Never
          volumes:
            - name: ucloud-multinode
              emptyDir: {}
