---
apiVersion: v1
kind: Service
metadata:
  name: project
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: project
      prefix: /api/projects/
      service: project:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: project