---
apiVersion: v1
kind: Service
metadata:
  name: app-license
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app-license
      prefix: ^/api/app/license(/.*)?$
      prefix_regex: true
      service: app-license:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-license
