---
apiVersion: v1
kind: Service
metadata:
  name: ping
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ping
      prefix: ^/api/ping(/.*)?$
      prefix_regex: true
      service: ping:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ping
