---
apiVersion: v1
kind: Service
metadata:
  name: accounting
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: accounting
      prefix: /api/accounting/
      service: accounting-service:8080

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: accounting-service