---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ serviceName }}-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ""
spec:
  rules:
  - host: cloud.sdu.dk
    http:
      paths:
      - path: /api/{{ serviceName }}
        backend:
          serviceName: {{ serviceName }}
          servicePort: 8080
