---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: registry.cloud.sdu.dk/sdu-cloud/notification-service:0.3.0
        command:
        - /opt/service/bin/service
        - --config-dir
        - /etc/psql
        - --config-dir
        - /etc/refresh-token
        volumeMounts:
        - mountPath: /etc/psql
          name: psql-secrets
        - mountPath: /etc/refresh-token
          name: refresh-token

      volumes:
      - name: psql-secrets
        secret:
          optional: false
          secretName: notification-psql
      - name: refresh-token
        secret:
          secretName: notification-refresh-token

      imagePullSecrets:
        - name: esci-docker
