---
apiVersion: v1
kind: Service
metadata:
  name: notification
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: notification
      prefix: /api/notifications/
      service: notification-service:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: notification-service