---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: indexing-service-deployment
  labels:
    app: indexing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexing-service
  template:
    metadata:
      labels:
        app: indexing-service
    spec:
      containers:
      - name: indexing-service
        image: registry.cloud.sdu.dk/sdu-cloud/indexing-service:1.14.4
        command:
        - /opt/service/bin/service
        - --config-dir
        - /etc/refresh-token
        volumeMounts:
        - mountPath: /etc/refresh-token
          name: refresh-token

      volumes:
      - name: refresh-token
        secret:
          optional: false
          secretName: indexing-refresh-token

      imagePullSecrets:
        - name: esci-docker
