version: "3.9"
services:
  redis:
    image: redis:5.0.9
    volumes:
      - redisData:/data
    hostname: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    hostname: elasticsearch

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ${PWD}/.compose/postgres:/var/lib/postgresql/data
      - ${PWD}/backend:/opt/ucloud
    ports:
    - ${POSTGRES_PORT:-35432}:5432
    hostname: postgres

  k3s:
    image: rancher/k3s:v1.21.6-rc2-k3s1
    privileged: true
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
    - /mnt/ceph:/mnt/cephfs
    - k3sConfig:/output
    - k3sData:/var/lib/rancher/k3s
    - k3sCni:/var/lib/cni
    - k3sKubelet:/var/lib/kubeley
    - k3sEtc:/etc/rancher
    command:
      - server
    hostname: k3s

  backend:
    image: dreg.cloud.sdu.dk/ucloud/ucloud:2021.3.0-alpha1
    user: root
    command:
      - /opt/service/bin/service
      - --dev
      - --config-dir
      - /etc/ucloud
    volumes:
      - ucloudData:/etc/ucloud
      - /mnt/ceph:/mnt/cephfs
      - k3sConfig:/mnt/k3s
    ports:
      - ${BACKEND_PORT:-8080}:8080
    restart: always
    depends_on:
      - redis
      - postgres
      - elasticsearch
      - k3s
    hostname: backend

  frontend:
    image: dreg.cloud.sdu.dk/ucloud/webclient:0.51.0-alpha4
    hostname: frontend

