version: "3.9"
services:
  integration-module:
    environment:
      - SLURM_CONF=/etc/slurm/slurm.conf
      - DATA_MOUNT=/data
    build:
      context: ./provider-integration/integration-module
      target: ucloud-im
    init: true
    # image: dreg.cloud.sdu.dk/ucloud/ucloud-dev:2021.2.0-storage2
    image: ucloud-im
    volumes:
      - imKonan:/root/.konan
      - imGradle:/root/.gradle
      - imData:/etc/ucloud
      - ~/.gradle/gradle.properties:/root/.gradle/gradle.properties
      - ${PWD}/provider-integration/integration-module:/opt/ucloud
      - m2Repo:/root/.m2
      - slurm_jobdir:/data
    volumes_from:
      - slurmdbd:ro
    command:
      - bash
      - -c
      - "bash /opt/ucloud-default-config/config_installer.sh ; tail -f /dev/null"
    depends_on:
      - backend
      - c2
    ports:
      - ${INTEGRATION_PORT:-8889}:8889
    hostname: integration-module
    labels:
      - "cluster=slurm"
