version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - keycloak:/opt/keycloak/data
    ports:
      - ${KEYCLOAK_PORT:-61241}:8080
    hostname: keycloak

