---
apiVersion: v1
kind: Service
metadata:
  name: file-gateway
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: file_gw_list
      prefix: ^/api/files(/(lookup|stat))?$
      prefix_regex: true
      rewrite: ""
      service: file-gateway:8080
      method: GET

spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: file-gateway
