---
master:
  persistence:
    storageClass: rbd
  heapSize: 2048m
  resources:
    limits:
      cpu: "2000m"
    requests:
      cpu: "2000m"
      memory: "4Gi"

data:
  replicas: 4
  persistence:
    storageClass: rbd
    size: 1000Gi
  heapSize: 12288m
  resources:
    limits:
      cpu: "8000m"
    requests:
      cpu: "8000m"
      memory: "25Gi"

client:
  heapSize: 2048m
  resources:
    limits: 
      cpu: "2000m"
    requests:
      cpu: "2000m"
      memory: "4Gi"

