apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.4.3
    component: client
    heritage: Tiller
    io.cattle.field/appId: elasticsearch
    release: elasticsearch
  name: elasticsearch-client-nodeport
  namespace: elasticsearch
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
    nodePort: 31920
  selector:
    app: elasticsearch
    component: client
    release: elasticsearch
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

