---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: ambassador
      config:
        diagnostics:
          enabled: false
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: ambassador
