---
apiVersion: v1
kind: Service
metadata:
  name: downtime-management
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: downtime-management
      prefix: ^/api/downtime(/.*)?$
      prefix_regex: true
      service: downtime-management:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: downtime-management
