application: v1

title: Syncthing
name: syncthing
version: 1

applicationType: WEB

web:
  port: 8384

allowMultiNode: false

tool:
  name: alpine
  version: 1

authors:
- Dan

container:
  runAsRoot: true
 
description: An application for synchronizing your files between your devices and UCloud. Powered by Syncthing.

parameters:
  stateFolder:
    optional: false
    title: "Folder to store state in"
    description: "This is where Syncthing will store its configuration and additional data"
    type: input_directory

invocation:
- sh
- -c
- >
  echo "Hello, World!";
  sleep 2;
  echo "How are you doing?";
  sleep 1;
  echo "This is just me writing some stuff for testing purposes!";
  sleep 1;
  seq 0 7200 | xargs -n 1 -I _ sh -c 'echo _; sleep 1';

outputFileGlobs:
  - "*"

