---
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app_hpc
      prefix: ^/api/hpc(/.*)?$
      prefix_regex: true
      service: app:8080
      rewrite: ""

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app_compute
      prefix: ^/api/app/compute(/.*)?$
      prefix_regex: true
      service: app:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-service