---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: storage-service

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: storage-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ""
spec:
  rules:
  - host: cloud.dev-sdu-cloud.dk
    http:
      paths:
      - path: /api/tus
        backend:
          serviceName: storage
          servicePort: 8080

      - path: /api/files
        backend:
          serviceName: storage
          servicePort: 8080

      - path: /api/shares
        backend:
          serviceName: storage
          servicePort: 8080

      - path: /api/upload
        backend:
          serviceName: storage
          servicePort: 8080
