---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: storage-service